"""
Monthly HTML Report Generator — OMEGA-1 requirement.
Generates per-month performance HTML for Jan 2022 → current month.
Produces one master combined HTML and sends a single email.
"""

import os
from datetime import datetime, date
from typing import List, Optional
from loguru import logger


_REPORT_DIR = os.path.join(os.path.expanduser("~"), "autotrader_reports", "monthly")
os.makedirs(_REPORT_DIR, exist_ok=True)


def _month_html(
    year: int,
    month: int,
    start_balance: float,
    end_balance: float,
    trade_count: int,
    win_count: int,
    loss_count: int,
    avg_rrr: float,
    max_drawdown: float,
    profit_factor: float,
    expectancy: float,
    best_pair: str,
    worst_pair: str,
    largest_winner_pips: float,
    largest_loser_pips: float,
) -> str:
    month_name = date(year, month, 1).strftime("%B %Y")
    ret_pct = (end_balance - start_balance) / start_balance * 100 if start_balance else 0.0
    win_rate = win_count / trade_count * 100 if trade_count else 0.0
    ret_color = "#2ecc71" if ret_pct >= 0 else "#e74c3c"
    return f"""
<div class="month-card">
  <h2>{month_name}</h2>
  <table>
    <tr><td>Start Balance</td><td>${start_balance:,.2f}</td></tr>
    <tr><td>End Balance</td><td>${end_balance:,.2f}</td></tr>
    <tr><td>Return</td><td style="color:{ret_color};font-weight:bold">{ret_pct:+.2f}%</td></tr>
    <tr><td>Win Rate</td><td>{win_rate:.1f}%</td></tr>
    <tr><td>Avg RRR</td><td>{avg_rrr:.2f}</td></tr>
    <tr><td>Max Drawdown</td><td>{max_drawdown:.2f}%</td></tr>
    <tr><td>Profit Factor</td><td>{profit_factor:.2f}</td></tr>
    <tr><td>Expectancy</td><td>{expectancy:.2f} pips</td></tr>
    <tr><td>Trade Count</td><td>{trade_count} ({win_count}W / {loss_count}L)</td></tr>
    <tr><td>Best Pair</td><td>{best_pair}</td></tr>
    <tr><td>Worst Pair</td><td>{worst_pair}</td></tr>
    <tr><td>Largest Winner</td><td>+{largest_winner_pips:.1f} pips</td></tr>
    <tr><td>Largest Loser</td><td>{largest_loser_pips:.1f} pips</td></tr>
  </table>
</div>
"""


_HTML_WRAPPER = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AutoTrader Claude — Monthly Reports</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background:#0d1117; color:#c9d1d9; margin:0; padding:20px; }}
  h1 {{ color:#58a6ff; border-bottom:1px solid #30363d; padding-bottom:10px; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(360px,1fr)); gap:20px; }}
  .month-card {{ background:#161b22; border:1px solid #30363d; border-radius:8px; padding:20px; }}
  .month-card h2 {{ color:#58a6ff; margin-top:0; font-size:1.1em; }}
  table {{ width:100%; border-collapse:collapse; }}
  td {{ padding:5px 8px; border-bottom:1px solid #21262d; font-size:0.9em; }}
  td:first-child {{ color:#8b949e; width:55%; }}
  td:last-child {{ font-weight:500; }}
  .generated {{ color:#484f58; font-size:0.8em; margin-top:30px; }}
</style>
</head>
<body>
<h1>AutoTrader Claude — Monthly Performance Reports</h1>
<p>Jan 2022 → {end_month} | Generated {generated_at}</p>
<div class="grid">
{cards}
</div>
<p class="generated">Generated by AutoTrader Claude OMEGA-1 system</p>
</body>
</html>"""


class MonthlyReportGenerator:
    """Generates monthly HTML performance reports from trade data."""

    def __init__(self, db=None):
        self.db = db

    def generate_all(
        self,
        trades_by_month: Optional[dict] = None,
        initial_balance: float = 10000.0,
        send_email: bool = False,
    ) -> str:
        """Generate monthly reports from Jan 2022 to current month.

        trades_by_month: dict of {(year, month): [BacktestTrade, ...]}
        If None, generates placeholder months with zero stats.

        Returns path to master combined HTML file.
        """
        now = datetime.utcnow()
        start = date(2022, 1, 1)
        end = date(now.year, now.month, 1)

        cards = []
        balance = initial_balance

        cur = start
        while cur <= end:
            year, month = cur.year, cur.month
            month_trades = []
            if trades_by_month:
                month_trades = trades_by_month.get((year, month), [])

            start_bal = balance
            wins = [t for t in month_trades if t.outcome == "win"]
            losses = [t for t in month_trades if t.outcome == "loss"]
            win_count = len(wins)
            loss_count = len(losses)
            trade_count = len(month_trades)

            avg_rrr = 0.0
            max_dd = 0.0
            pf = 0.0
            exp = 0.0
            best_pair = "XAUUSD"
            worst_pair = "XAUUSD"
            lw = 0.0
            ll = 0.0

            if month_trades:
                rrrs = [t.rrr_achieved for t in month_trades if t.rrr_achieved]
                avg_rrr = sum(rrrs) / len(rrrs) if rrrs else 0.0
                gp = sum(t.pnl_pips or 0 for t in wins)
                gl = abs(sum(t.pnl_pips or 0 for t in losses))
                pf = gp / gl if gl > 0 else 0.0
                wr = win_count / trade_count
                avg_win = gp / win_count if win_count else 0.0
                avg_loss = gl / loss_count if loss_count else 0.0
                exp = (wr * avg_win) - ((1 - wr) * avg_loss)
                win_pips = [t.pnl_pips or 0 for t in wins]
                loss_pips = [t.pnl_pips or 0 for t in losses]
                lw = max(win_pips) if win_pips else 0.0
                ll = min(loss_pips) if loss_pips else 0.0

                pairs = {}
                for t in month_trades:
                    pairs.setdefault(t.pair, []).append(t.pnl_pips or 0)
                pair_pnl = {p: sum(v) for p, v in pairs.items()}
                best_pair = max(pair_pnl, key=pair_pnl.get) if pair_pnl else "XAUUSD"
                worst_pair = min(pair_pnl, key=pair_pnl.get) if pair_pnl else "XAUUSD"

                total_pct = sum(t.pnl_pct or 0 for t in month_trades) / 100
                balance += initial_balance * total_pct
                max_dd = max(
                    (abs(t.pnl_pct or 0) for t in losses), default=0.0
                )

            cards.append(_month_html(
                year=year, month=month,
                start_balance=start_bal,
                end_balance=balance,
                trade_count=trade_count,
                win_count=win_count,
                loss_count=loss_count,
                avg_rrr=avg_rrr,
                max_drawdown=max_dd,
                profit_factor=pf,
                expectancy=exp,
                best_pair=best_pair,
                worst_pair=worst_pair,
                largest_winner_pips=lw,
                largest_loser_pips=ll,
            ))

            month_html_path = os.path.join(_REPORT_DIR, f"{year}_{month:02d}.html")
            _write_single_month(year, month, cards[-1], month_html_path)

            # advance month
            if month == 12:
                cur = date(year + 1, 1, 1)
            else:
                cur = date(year, month + 1, 1)

        end_month = f"{end.strftime('%B %Y')}"
        generated_at = now.strftime("%Y-%m-%d %H:%M UTC")
        combined = _HTML_WRAPPER.format(
            end_month=end_month,
            generated_at=generated_at,
            cards="\n".join(cards),
        )
        master_path = os.path.join(_REPORT_DIR, "combined_monthly_report.html")
        with open(master_path, "w", encoding="utf-8") as f:
            f.write(combined)

        logger.info(f"Monthly HTML report generated: {master_path}")

        if send_email:
            self._email_report(master_path, end_month)

        return master_path

    def _email_report(self, path: str, end_month: str):
        try:
            from alerts.email_alert import EmailAlert
            ea = EmailAlert()
            with open(path, "r", encoding="utf-8") as f:
                body = f.read()
            ea.send(f"AutoTrader Monthly Report — {end_month}", body)
        except Exception as e:
            logger.error(f"Monthly report email failed: {e}")


def _write_single_month(year: int, month: int, card_html: str, path: str):
    month_name = date(year, month, 1).strftime("%B %Y")
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{month_name} — AutoTrader Claude</title>
<style>
  body{{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;padding:20px}}
  .month-card{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:20px;max-width:400px}}
  .month-card h2{{color:#58a6ff;margin-top:0}}
  table{{width:100%;border-collapse:collapse}}
  td{{padding:5px 8px;border-bottom:1px solid #21262d;font-size:0.9em}}
  td:first-child{{color:#8b949e;width:55%}}
</style>
</head>
<body>
{card_html}
</body>
</html>"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
